# Applies comments from a txt file generated by IDR (https://github.com/crypto2011/IDR)
#@author Johannes Mittendorfer
#@category Delphi
#@keybinding 
#@menupath Tools.Delphi.Comments
#@toolbar 

from ghidra.program.model.listing import CodeUnit
from ghidra.program.model.address import Address

def read_file(filename):
	return open(filename).read()

def parse_file(contents):
	lines = contents.split("\r\n")
	return map(parse_line, lines)

def parse_line(line):
	parts = line.split(" ")

	if(len(parts) < 3):
		print("Wrong size: " + line)
		return None

	return (parts[1], parts[2])

def apply_comments(comments):
	for comment in comments:
		apply_comment(comment)

def apply_comment(comment):
	if(comment is None):
		return

	addr = currentProgram.getAddressFactory().getAddress(comment[0])
	code_unit = currentProgram.getListing().getCodeUnitAt(addr)
	if(code_unit is None):
		return	

	code_unit.setComment(CodeUnit.EOL_COMMENT, comment[1])

contents = read_file("<path to txt file>")
comments = parse_file(contents)
apply_comments(comments)
